### ISSUE TITLE
js请求的URL中含有重复的斜杠

### ISSUE THREAD

**Issue by hycinth22** [lingmm/yilia-theme-port-to-typecho#2]
at /js/main.js
`require([yiliaConfig.base_url+'/js/....`

yiliaConfig.base_url已经包含结尾/，造成发出/usr/yilia**//**js/xxx.js的请求，URL中含有重复斜杠。
部分未对此作处理的Web Server下可能造成404或其他错误

**Comment by impasse** [comment]
thank you~
