### ISSUE TITLE
你好   我使用了你的模板  但是post页面的JS文件报错  麻烦看一下  谢谢

### ISSUE THREAD

**Issue by wujunze** [lingmm/yilia-theme-port-to-typecho#3]
https://wujunze.duoshuo.com.duoshuo.com/api/threads/listPosts.json?thread_k…%2Cunread%2Clog%2CextraCss&referer=https%3A%2F%2Fwujunze.com%2F&v=15.11.15 net::ERR_INSECURE_RESPONSES.API.ajax @ embed.js:1S.API.get @ embed.js:1(anonymous function) @ embed.js:2r.extend.each @ embed.compat.js?24f8ca3f.js:1r.fn.r.each @ embed.compat.js?24f8ca3f.js:1S.initSelector @ embed.js:2r.extend.each @ embed.compat.js?24f8ca3f.js:1S.initView @ embed.js:2(anonymous function) @ embed.js:2(anonymous function) @ embed.js:1r.onload.r.onreadystatechange @ embed.js:1

**Comment by impasse** [comment]
多说域名配置错了吧。。
